"""Scan wallpaper folders and synchronise the database + thumbnails.

Looks in the configured wallpapers_dir for subfolders containing a
manifest.json. Generates thumbnails (Pillow for images, VLC snapshot for
video, screenshot for web/interactive when possible). New wallpapers are
added; removed ones are dropped from the DB (but their collections keep
dangling-safe via FK SET NULL).
"""
from __future__ import annotations

import shutil
from pathlib import Path

from ..core.config import Config
from ..core.logger import setup_logger
from ..database.database import Database
from ..wallpaper.loader import load
from ..wallpaper.metadata import Manifest

log = setup_logger("wallforge.indexing")

THUMB_SIZE = (320, 180)


def _make_thumbnail(src: Path, dst: Path) -> bool:
    try:
        from PIL import Image
        dst.parent.mkdir(parents=True, exist_ok=True)
        with Image.open(src) as im:
            im = im.convert("RGB")
            im.thumbnail(THUMB_SIZE, Image.LANCZOS)
            im.save(dst, "JPEG", quality=82)
        return True
    except Exception as exc:
        log.warning("thumbnail failed for %s: %s", src, exc)
        return False


def index_directory(db: Database, root: Path) -> int:
    count = 0
    existing_paths = {w.path for w in db.list_wallpapers()}
    seen = set()
    for folder in sorted(p for p in root.iterdir() if p.is_dir()):
        try:
            manifest, content = load(folder)
        except Exception as exc:
            log.debug("skip %s: %s", folder, exc)
            continue
        seen.add(str(folder))
        thumb = folder / "thumbnail.jpg"
        if not thumb.exists():
            if manifest.type == "image":
                _make_thumbnail(content, thumb)
            # video/web/interactive thumbnails generated by renderer at runtime
        w = db.upsert_wallpaper(_row_from(folder, manifest, thumb))
        count += 1
        if str(folder) not in existing_paths:
            log.info("indexed: %s (%s)", manifest.name, manifest.type)
    # Drop folders that no longer exist.
    for w in db.list_wallpapers():
        if w.path not in seen and Path(w.path).exists() is False:
            db.delete_wallpaper(w.id)
    return count


def _row_from(folder: Path, m: Manifest, thumb: Path | None):
    from ..database.models import Wallpaper
    return Wallpaper(
        id=None, title=m.name, author=m.author, type=m.type, path=str(folder),
        thumbnail=str(thumb) if thumb and thumb.exists() else None,
        preview=str(folder / "preview.jpg") if (folder / "preview.jpg").exists() else None,
        favorite=0, created_at=None, tags=",".join(m.tags),
    )


def index_all(db: Database, config: Config) -> int:
    root = Path(config.wallpapers_dir)
    root.mkdir(parents=True, exist_ok=True)
    return index_directory(db, root)


if __name__ == "__main__":
    from ..core.config import Config
    from ..database.database import Database
    c = Config.load()
    d = Database()
    print("indexed", index_all(d, c), "wallpapers")
    d.close()
